import React from "react";
import type { Metadata } from "next";
import { RefineContextProvider } from "./providers";
import "@refinedev/antd/dist/reset.css";

export const metadata: Metadata = {
  title: "Create R3 App",
  description: "Generated by create-r3-app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <RefineContextProvider>
          {children}
        </RefineContextProvider>
      </body>
    </html>
  );
}